### ISSUE TITLE
Organize files

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/group-procedures#2]
It would probably be nice to put the chapter .qmd files into folders by part.

E.g. mimic this organization:

https://github.com/cct-datascience/group-procedures/blob/36047e7d4e0b03647dde4a0f58382b5eeac66a70/_quarto.yml#L10-L21

Would also have to update paths in _quarto.yml likely

**Comment by Aariq** [comment]
ehh.. maybe not so important?

**Comment by Aariq** [comment]
I thought I saw something about it being possible to reference a directory under `chapters:` but it seems that is not the case.  Things I've tried that haven't worked:

``` yaml
chapters:
  - vignettes

chapters: 
  - vignettes/
 
chapters:
  - "vignettes/"

chapters:
  - "vignettes/*"

chapters:
  - href: "vignettes/*"

```
